# Exported from Render on 2024-09-08T03:52:24Z
services:
  - type: web
    name: ProgramMeServer
    runtime: docker
    repo: https://github.com/IsmailAbousalem/ProgramMeServer
    branch: postgreSQL
    plan: free
    region: virginia
    dockerContext: .
    dockerfilePath: ./Dockerfile
version: "1"
